### ISSUE TITLE
jags.basic suppresses console output when parallel = true despite verbose = true

### ISSUE THREAD

**Issue by jasanford** [kenkellner/jagsUI#6] opened 2016-01-05 18:59 UTC
The process runs fine and output is correct. I'm calling jags.basic via BESTmcmc (which passes verbose and parallel straight through to jags.basic. Perhaps console output wouldn't be useful but automatic suppression isn't mentioned in the documentation that I could find so it feels like a bug.

Versions: R 3.2.2, BEST 0.3.0, jagsUI 1.3.7, rjags 4-4, JAGS 4.0.1

Sample script and terminal output:

BESTout <- BESTmcmc(y1, y2, parallel = TRUE, verbose = TRUE)
Processing function input.......

Done.

Beginning parallel processing with 3 clusters. Console output will be suppressed.

**Comment by kenkellner** [comment] 2016-01-06 16:43
It's not a bug as much as a limitation. It's a consequence of the way the 'parallel' package works (which is what jagsUI is using in the background here). Each chain is being offloaded to a separate child process (each with its own invisible console) and there is no easy way to track their progress back in the parent R session until the run is complete. That's why jagsUI states "console output will be suppressed" (maybe I should state that more clearly in the warning message).

In the past I have explored some workarounds involving sending progress from the child processes to an exterior file which could then be read by the parent R session perhaps allowing for some kind of progress bar. I'll probably look at that again in the future although I'm concerned it might negatively impact performance.

**Comment by jasanford** [comment] 2016-01-06 19:45
I wouldn't want to compromise performance just to satisfy the annoyance of staring at a black box. But I agree making the warning more explicit about function behavior is a good idea.

On Jan 6, 2016, at 10:43 AM, Ken Kellner <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not a bug as much as a limitation. It's a consequence of the way the 'parallel' package works (which is what jagsUI is using in the background here). Each chain is being offloaded to a separate child process (each with its own invisible console) and there is no easy way to track their progress back in the parent R session until the run is complete. That's why jagsUI states "console output will be suppressed" (maybe I should state that more clearly in the warning message).

In the past I have explored some workarounds involving sending progress from the child processes to an exterior file which could then be read by the parent R session perhaps allowing for some kind of progress bar. I'll probably look at that again in the future although I'm concerned it might negatively impact performance.

-
Reply to this email directly or view it on GitHub<https://github.com/kenkellner/jagsUI/issues/6#issuecomment-169383495>.

----------------------------------------------------------------------
Confidentiality Notice: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by jasanford** [comment] 2016-01-07 05:37
I wouldn't want to compromise performance just to satisfy the annoyance of staring at a black box. But I agree making the warning more explicit about function behavior is a good idea.

On Jan 6, 2016, at 10:43 AM, Ken Kellner <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not a bug as much as a limitation. It's a consequence of the way the 'parallel' package works (which is what jagsUI is using in the background here). Each chain is being offloaded to a separate child process (each with its own invisible console) and there is no easy way to track their progress back in the parent R session until the run is complete. That's why jagsUI states "console output will be suppressed" (maybe I should state that more clearly in the warning message).

In the past I have explored some workarounds involving sending progress from the child processes to an exterior file which could then be read by the parent R session perhaps allowing for some kind of progress bar. I'll probably look at that again in the future although I'm concerned it might negatively impact performance.

—
Reply to this email directly or view it on GitHub<https://github.com/kenkellner/jagsUI/issues/6#issuecomment-169383495>.

----------------------------------------------------------------------
Confidentiality Notice: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by kenkellner** [comment] 2016-02-10 22:11
I have spent some time looking into this and haven't found a useful way to monitor the child processes, so I'm closing this issue for now.

**Closed** 2018-01-12 16:31 UTC
Labels: enhancement
